### ISSUE TITLE
Hello,Dear Friend,Is there a way to use LL USBIO on normal pc?

### ISSUE THREAD

**Issue by llsifac** [641i130/ttx4-usbio#1]
Thanks for your responce yesterday,
Now I can play all songs and all difficulty by modded files from your source.
now I want rewrite the files in vdimg_ec.img So I can play it all on original cabinet,Is there a way to open it and rewrite the files in it?
I have LL USBIO THAT WANT TO use it on normal pc,
if it's working,I can play it with original controller,how can i drive it on normal pc?
it seems the normal pc can not recognize it.
Thanks in advance.

**Comment by 641i130** [comment]
The TTX4 USB IO card needs external power to work. Do you have the power source from the original machine? If not, you will have to diy it yourself. I can help you in more depth on the discord. Please message me there. `@caretchara`
